# Generated by Django 3.2.7 on 2021-09-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.DateTimeField(verbose_name='Text of comment.')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data of create post.')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Data of edit post.')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='If moderated')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text of kit')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data of create kit')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Data of edit kit')),
                ('views', models.BigIntegerField(default=0, verbose_name='Count of view.')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='If moderated')),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
                'db_table': 'kits',
            },
        ),
    ]
